# Generated by Django 5.0.3 on 2024-04-08 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='TMSapp.company'),
        ),
    ]
