# Generated by Django 5.0.3 on 2024-04-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSapp', '0003_alter_company_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile_pics/default_profile_picture.png', upload_to='profile_pics/'),
        ),
    ]
