# Generated by Django 5.0.3 on 2024-04-04 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSapp', '0005_remove_driver_title_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='TMSapp.company'),
            preserve_default=False,
        ),
    ]
