# Generated by Django 4.2.3 on 2024-03-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMSapp', '0007_yourmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='category',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
