# Generated by Django 5.0.3 on 2024-03-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMSapp', '0009_company_remove_message_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='first_name',
            field=models.CharField(default='DefaultFirstName', max_length=30),
        ),
        migrations.AddField(
            model_name='manager',
            name='last_name',
            field=models.CharField(default='DefaultLastName', max_length=30),
        ),
        migrations.AddField(
            model_name='manager',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='title',
            field=models.CharField(default='Manager', max_length=100),
        ),
    ]
